#https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

name: shells
on: [push]
jobs:
  Testing-multiple-shells:
    runs-on: ubuntu-latest
    steps:
      - name: python command
        run: |
          import platform
          print(platform.processor())
          print(platform.python_version())
        shell: python
